# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'assistance_gui.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_assistance_gui(object):
    def setupUi(self, assistance_gui):
        assistance_gui.setObjectName("assistance_gui")
        assistance_gui.resize(789, 600)
        self.centralwidget = QtWidgets.QWidget(assistance_gui)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(-10, 0, 811, 601))
        self.label.setStyleSheet("background:transparent;\n"
                                 "border radius:none;")
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("jarvis_images/speech.gif"))
        self.label.setScaledContents(False)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(520, 10, 261, 201))
        self.label_2.setText("")
        self.label_2.setPixmap(QtGui.QPixmap("jarvis_images/heart.gif"))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(0, 0, 401, 131))
        self.label_3.setText("")
        self.label_3.setPixmap(QtGui.QPixmap("jarvis_images/initialse.gif"))
        self.label_3.setScaledContents(True)
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(510, 380, 271, 211))
        self.label_4.setText("")
        self.label_4.setPixmap(QtGui.QPixmap("jarvis_images/rat.gif"))
        self.label_4.setScaledContents(True)
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(10, 400, 271, 191))
        self.label_5.setText("")
        self.label_5.setPixmap(QtGui.QPixmap("jarvis_images/2voice_recognition_process_by_gleb.gif"))
        self.label_5.setScaledContents(True)
        self.label_5.setObjectName("label_5")
        # self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        # self.pushButton.setGeometry(QtCore.QRect(300, 570, 75, 23))
        # self.pushButton.setStyleSheet("background-color: rgb(0, 170, 0);")
        # self.pushButton.setObjectName("pushButton")
        # self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget)
        # self.pushButton_2.setGeometry(QtCore.QRect(390, 570, 75, 23))
        # self.pushButton_2.setStyleSheet("background-color: rgb(170, 0, 0);")
        # self.pushButton_2.setObjectName("pushButton_2")
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(-30, 90, 391, 161))
        self.label_6.setText("")
        self.label_6.setTextFormat(QtCore.Qt.AutoText)
        self.label_6.setPixmap(QtGui.QPixmap("jarvis_images/datetime.jpg"))
        self.label_6.setScaledContents(True)
        self.label_6.setObjectName("label_6")
        self.textBrowser = QtWidgets.QTextBrowser(self.centralwidget)
        self.textBrowser.setGeometry(QtCore.QRect(50, 150, 111, 41))
        self.textBrowser.setStyleSheet("background:transparent;\n"
                                       "border-radius:none;font-size:20px; color:white;")
        self.textBrowser.setObjectName("textBrowser")
        self.textBrowser_2 = QtWidgets.QTextBrowser(self.centralwidget)
        self.textBrowser_2.setGeometry(QtCore.QRect(170, 150, 111, 41))
        self.textBrowser_2.setStyleSheet("background:transparent;\n"
                                         "border-radius:none;font-size:20px; color:white;")
        self.textBrowser_2.setObjectName("textBrowser_2")
        assistance_gui.setCentralWidget(self.centralwidget)

        self.retranslateUi(assistance_gui)
        QtCore.QMetaObject.connectSlotsByName(assistance_gui)

    def retranslateUi(self, assistance_gui):
        _translate = QtCore.QCoreApplication.translate
        assistance_gui.setWindowTitle(_translate("assistance_gui", "Assistance || Coded By codewithcup"))
        # self.pushButton.setText(_translate("assistance_gui", "Execute"))
        # self.pushButton_2.setText(_translate("assistance_gui", "Terminate"))


if __name__ == "__main__":
    import sys

    app = QtWidgets.QApplication(sys.argv)
    assistance_gui = QtWidgets.QMainWindow()
    ui = Ui_assistance_gui()
    ui.setupUi(assistance_gui)
    assistance_gui.show()
    sys.exit(app.exec_())
